######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 6 23:33:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    spreadsheet.h \
    cell.h
FORMS += gotocelldialog.ui sortdialog.ui
SOURCES += main.cpp mainwindow.cpp \
    spreadsheet.cpp \
    cell.cpp
RESOURCES += spreadsheet.qrc
